name: Symfony CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: democatalogue
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql      
      - name: Install dependencies
        run: composer install
      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            mysql -h 127.0.0.1 -u symfony -psymfony -e "SELECT 1" && break
            echo "Waiting for MySQL..."
            sleep 5
          done
      - name: Prepare database
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test
      - name: Run tests
        env:
          DATABASE_URL: mysql://symfony:symfony@127.0.0.1:3306/democatalogue_test
          MAILER_DSN: "smtp://127.0.0.1:1025"
        run: php bin/phpunit --testdox
